development: &default
  adapter: postgresql
  database: slackdj_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: slackdj_test
